name: ROS build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ros2
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.3.3
        with:
          target-ros2-distro: foxy
